export const latestPropertyData = [
  {
    id: 1,
    imageSrc: "/images/home2.jpeg",
    title: "Luxury Apartment in Gandhi Road",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹16 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },  {
    id: 2,
    imageSrc: "/images/home2.jpeg",
    title: "Luxury Apartment in Gandhi Road",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹16 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },  {
    id: 3,
    imageSrc: "/images/home2.jpeg",
    title: "Luxury Apartment in Gandhi Road",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹16 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },  {
    id: 4,
    imageSrc: "/images/home2.jpeg",
    title: "Luxury Apartment in Gandhi Road",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹16 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },  {
    id: 5,
    imageSrc: "/images/home2.jpeg",
    title: "Luxury Apartment in Gandhi Road",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹16 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },
];
