export const propertyListData = [
  {
    id: 1,
    imageSrc: "/images/home2.jpeg",
    title: "Luxury Apartment in Gandhi Road",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹16 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },
  {
    id: 2,
    imageSrc: "/images/home3.jpeg",
    title: "Modern Family Home",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹76 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },
  {
    id: 3,
    imageSrc: "/images/home4.jpeg",
    title: "Spacious Villa",
    size: "450 meters",
    location: "Ahmedabad",
    price: "₹46 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },
  {
    id: 4,
    imageSrc: "/images/home5.jpeg",
    title: "Cozy Cottage",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹22 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },
  {
    id: 5,
    imageSrc: "/images/home6.jpg",
    title: "Elegant Residence",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹16 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },
  {
    id: 6,
    imageSrc: "/images/home8.jpeg",
    title: "Contemporary House",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹76 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },
  {
    id: 7,
    imageSrc: "/images/home2.jpeg",
    title: "Charming Home",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹76 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },
  {
    id: 8,
    imageSrc: "/images/home1.avif",
    title: "Stylish Apartment",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹76 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },
  {
    id: 9,
    imageSrc: "/images/home4.jpeg",
    title: "Modern Studio",
    size: "5150",
    bed:"2",
    bath:"3",
    location: "Ahmedabad",
    price: "₹76 Lakh",
    address: "Gandhi Road, Ahmedabad",
  },
];
